### ISSUE TITLE
Add support for Scala Pickling library

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finagle-serial#3]
Github page: https://github.com/scala/pickling

**Comment by vkostyukov** [comment]
We probably should use similar approach to http://stackoverflow.com/questions/18725699/scala-pickling-and-type-parameters.

**Comment by cocodrino** [comment]
Hello!!.. @vkostyukov did you recommend picking for simple projects instead of thrift?..I've heard than frecuently picking fails decoding, the addon is in a tree and not has been added to the master branch since Jan 6, so I suppose than scodec was prioritized over picking ...2) How use it? is it so simple as you show here https://github.com/finagle/finagle-serial/tree/d24aefb27924a09a6343156b5db75b0e7cbda30a ?

**Comment by vkostyukov** [comment]
Hi @cocodrino!

Scodec is a default setting for finagle-serial for now and I would say that it's pretty workable for small projects. Although, I personally haven't tried it in the wild. In order to understand basic concepts, I encourage you have a look at @travisbrown's [post about finagle-serial](https://finagle.github.io/blog/2015/02/06/finagle-services-made-simple-with-serial/).

Please let us know if you have any questions regarding finagle-serial. We're thrilled to know that somebody is using it (perhaps in production?).

**Comment by cocodrino** [comment]
thanks  for the link @vkostyukov I'll  probably use it for a super simple small project first but looks promising.
